<?php
/**
 * SendPulse_Mageia Magento component
 *
 * @category    SendPulse
 * @package     SendPulse_Mageia
 * @author      SendPulse Team <info@sendpulse.com>
 * @copyright   SendPulse (http://sendpulse.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">

    <h4>
        <img src="http://sendpulse.com/wp-content/themes/sendpulse/img/logo.png?<?php echo $this->getPxParams(); ?>"/><br><br>
        <div style="padding-left: 30px;">
            <p> <strong style="color:#EA7601;"><?php echo __('Mageia v') ?><?php echo $this->getVersion() ?><?php echo __(' by') ?></strong> <a target="_blank" href="http://sendpulse.com"><strong>SendPulse</strong></a></p>
            <p><?php echo __('Need help? See our ') ?><a href="https://sendpulse.com/support/index.php?type=page&urlcode=969532&title=Knowledge-Base&r=1" target="_blank"><?php echo __('Knowlege Base') ?></a>. <?php echo __(' Got feedback? ') ?><a href="mailto:info@sendpulse.com?Subject=Mageia Version <?php echo $this->getVersion()?>"><?php echo __('Email us') ?></a></p>
            <p><?php echo __('You can also visit ') ?><a href="https://sendpulse.com/blog" target="_blank"><?php echo __('our blog') ?></a></p>
            <h3><a style="padding-top: 5px;padding-bottom:5px;padding-left: 30px;padding-right: 30px;background-color:#EB5202 ;color:white;font-weight: bold" href="https://sendpulse.com/register&source=megento" target="_blank"><?php echo __('Support Mageia, Subscribe for a free SendPulse Account!') ?></a> </h3>
        </div>
    </h4>
</div>